### ISSUE TITLE
Favorite apps shouldn’t be duplicated in all apps list

### ISSUE THREAD

**Issue by jancborchardt** [light-launcher/Light-Android-Launcher#12]
Currently favorite apps are displayed twice. Once in the favorites list and then again in the all apps list. This is unnecessary duplication and it would be much nicer to only show them once. This would also make the all apps list shorter.

The one issue is that long-press in the all apps list is used to show app details, and in favorites it’s used to pick the favorite app.

What we could do is in the favorites app picker, if you long-press on a used slot it, the dialog will show "`Appname` info" as the first entry.

**Comment by postapczuk** [comment]
done in 1.7
