### ISSUE TITLE
Prepopulate some favorite entries for better first run?

### ISSUE THREAD

**Issue by jancborchardt** [light-launcher/Light-Android-Launcher#14]
Currently people who install the app for the first time are faced with a very bland and technical view:

> Long-press to pick app
> Long-press to pick app
> Long-press to pick app
> Long-press to pick app
> Long-press to pick app

We could prepopulate some entries like messaging app, phone and clock just to have a better first run experience. Just like Light Phone II does.

@postapczuk you said:

> It was in the first version, but alot of users asked to change it. You think about this app as smartphone one as I did, but some older Androids and tablets have different names of actions to run the Contacts and Messaging. My Idea was to keep it simply stupid and work for wide versions of Android, so it is harder to maintain.

Right, but we could have some sane defaults, and the fallback can still be empty. It would be cool to have it at least like this:

> Clock
> Phone
> Messages
> Long-press to pick app
> Long-press to pick app

For "Messages" we could simply check what’s set as the default SMS app in the system? Or otherwise have an array of possible messenger names, and pick one. And you could of course still long-press on any entry to change the app.

The point is not to have it exact and work for everyone, it’s just so that people get a little feeling for how it would look like, and not uninstall it directly because they have no clue how to use it. :)

**Comment by jancborchardt** [comment]
@mugdhosapiens  @mjray could you advise here :)
- What is the name or package name of the phone app you would want to see automatically added? (We could have a priority list, cause if you installed a custom phone app you probably want that to show up)
- Did you disable the system app then?
- Why does it show up as "Android system"? Does it still launch a phone app?

**Comment by postapczuk** [comment]
Because of different app pakages for each system we can't populate the apps
