### ISSUE TITLE
Sort apps by frequency of use

### ISSUE THREAD

**Issue by jancborchardt** [light-launcher/Light-Android-Launcher#15]
Currently the AllAppsActivity is sorted alphabetically. That’s quite bad for apps like VLC or Signal. ;)

If we get the data somewhere, we could sort them by frequency of use which is a much more useful metric.

@postapczuk you wrote:

> A lot of people wrote on Reddit that they hate this feature in launchers. I think it is good idea to give them choice to use that feature :)

I’m fine adding a setting there, on the bottom of the all apps list for example which just toggles the sorting "Sort by name"/"Sort by usage". Remember that we need to maintain all settings though. :)

**Comment by jancborchardt** [comment]
> we allow people to pin apps to the top

We already have the favorites view, which is basically pinning. :)

The issue with manual pinning is also that it's extra work everyone has to do. I'd like to help people spend less time on their phones, and automatic intelligent sorting is one part to improve that.

Search bar I agree with, as long as it's subdued. Could you open a separate issue for that? :)

**Comment by snug** [comment]
@jancborchardt Might need some clarification on how to access the favourites view, I can't seem to figure it out.

**Comment by jancborchardt** [comment]
> Might need some clarification on how to access the favourites view, I can't seem to figure it out.

That’s the main view with the 5 app slots – we can see if "favorites view" is the proper name we can use. :) And the "all apps" list is the one you reach by swiping to the side.

**Comment by jancborchardt** [comment]
I think we talk about different things. Your last sentence Is basically what I’m talking about. ;)

- The "Favorites view", the default view with the user-configurable apps is great how we do it now. Will even be better when you can choose _less_ than 5 apps.
- What I’m talking about regarding sorting here, is only for the "All apps" view which you swipe to. It’s like "I need to access one of my non-favorites, but it’s called 'VLC' and just because of the name I need to scroll all the way down, even though I use it often."

The point being that apps which start with A or B are not really the most relevant, so alphabetic sorting is not really sensible.

**Comment by postapczuk** [comment]
Search bar added, feature with order won't be applied
