### ISSUE TITLE
Possible to add app to favorites multiple times

### ISSUE THREAD

**Issue by jancborchardt** [light-launcher/Light-Android-Launcher#28]
Currently it’s possible to add an application to favorites lots of times, which doesn’t really make sense. :)

Any app which already is in favorites, should be excluded from the "Pick an app" dialog.

**Comment by taylor-josh** [comment]
I'll give this one a shot.
I was thinking even just a toast message letting you know that the app was already in your favourites might be adequate/easier to maintain. Thoughts?

**Comment by jancborchardt** [comment]
@taylor-josh it would be good to directly exclude the apps from the picker. Showing a toast is not really a nice flow, as we can already catch it before. It also helps to reduce the list of apps from which you can pick. :)

Btw, very related to this issue: **Favorite apps shouldn’t be duplicated in all apps list #12** – if you want to look into that too.

**Comment by taylor-josh** [comment]
Yeah, I can check it #12 as well when I did into this issue.

**Comment by postapczuk** [comment]
done in 1.7
