### ISSUE TITLE
Change launcher font

### ISSUE THREAD

**Issue by snug** [light-launcher/Light-Android-Launcher#32]
Hey, do you guys think that it might be nice to change the launcher's font?

Personally, I like the look of Montserrat (Thin or Light) as a default font, but perhaps there should be options for a user to select what font they want?
https://fonts.google.com/specimen/Montserrat

**Comment by snug** [comment]
I have a development environment at home, so might have a go at doing this one myself 👍 hopefully I don't fuck it up too bad.

**Comment by jancborchardt** [comment]
> might be nice to change the launcher's font?
> Personally, I like the look of Montserrat (Thin or Light) as a default font

Not sure about this one. From a typography point of view, in this case it’s best when it’s not obtrusive. And using Roboto as it’s the system default typeface (and also quite nice) is already really good.

We should definitely not use any Thin or Light version of a typeface as it is not very readable or accessible.

We could try with Montserrat Regular.


> but perhaps there should be options for a user to select what font they want?

There are some issues with settings or options, especially for something like a typeface:
- They make people spend more time on their phones, which is what we don’t really want
- We should already design it properly
- People rarely change the default anyway
- We would need to test and maintain all the different option states, which takes away time and resources

Recommended reading: [Choosing our preferences](https://ometer.com/preferences.html).

**Comment by snug** [comment]
@jancborchardt Thanks for linking that article, that's a really, really good point and it's changed my mind on the whole thing.

I'm not a big fan of Roboto truth be told, lots of nicer fonts, but you're right about the thin fonts, and Montserrat Regular looks good, could have a go with that.

**Comment by github-tomster** [comment]
@snug 
also a good read is this one: https://github.com/nextcloud/android/issues/3348
so if you change the font from system default, do not FORGET to give the user
the option to choose if he wants to or not...
@those-assembling-the-code
for an unworthy user like me it is the worst case to use an 'application' that forces
a font to me...
and maybe other users like me exist out there!

**Comment by postapczuk** [comment]
I agree with Tomster. Simplicity is the power

**Comment by jancborchardt** [comment]
@github-tomster do note that lots of your comments in the Nextcloud issue thread you linked were marked as disruptive. So it would be cool if it doesn’t end up the same here.


Regarding the original issue: Let’s then stay with the Android default font. Right now it’s Roboto, but for upcoming versions it seems there’s a new one which is more round, kind of similar to Montserrat. Will close the issue hence.
