### ISSUE TITLE
Move to organization on Github

### ISSUE THREAD

**Issue by jancborchardt** [light-launcher/Light-Android-Launcher#34]
Currently we still have not so many contributions and the occasional regression through a direct push to master.

In other projects I’m working on, we do it like this:
- Have an organization on Github (I created https://github.com/light-launcher and invited you @postapczuk as owner) →  it feels more like a group effort because we have a group organization :tada: 
- That way people can collaboratively set labels and milestones → we can properly set a roadmap and priorities
- We use branch protection for the master branch so that everything goes through pull requests with 1 (or 2) required reviews. → This helps a lot catch issues early, and make others aware of what everyone is working on.

What do you think @postapczuk @snug and others?

**Comment by postapczuk** [comment]
I'll accept the invitation and check what this implies

**Comment by postapczuk** [comment]
There is one little problem about this whole thing - as I can see if I move the repo to the organization the url will change. If so We need to change the source of building app on f-droid. 

Also, if the app package will change from com.github.postapczuk.lalauncher the f-droid and android systems wouldn't recognize this as the same app and all users used it won't get new updates as it will be threaten as the new application.

We need to discuss how to do it properly.

**Comment by jancborchardt** [comment]
An intermediate step to do this would be to add others as collaborators in the settings of this repository. :)

Also, we should set the master branch to protected as well with 1 or 2 required reviews – that is in the repository settings too.

This already fixes point 2 and 3, and we can still see to move to an organization?

**Comment by postapczuk** [comment]
point 2 and 3 done

**Comment by jancborchardt** [comment]
@postapczuk thank you, that makes working on the app much easier! :) If it’s ok I would at some point go through the issues and assign the proper labels (e.g. either "bug" or "enhancement", and "good first issue" for small issues to get people involved) and also maybe see about milestones just for rough planning. :)
