### ISSUE TITLE
applicatiom freezes when click "back" on all apps view

### ISSUE THREAD

**Issue by postapczuk** [light-launcher/Light-Android-Launcher#40]
How to reproduce:
1. Swipe to all apps view
2. Press "back" button

Expected:
Go back to the favourites

Now:
Fereeze with black screen

**Comment by jancborchardt** [comment]
Hm, can actually not confirm, it works fine for me. Android 8.1 with latest master app.

**Comment by postapczuk** [comment]
So it's harder to reproduce...

**Comment by postapczuk** [comment]
No longer appears

**Comment by jancborchardt** [comment]
Yup, can confirm it's fixed with the new view switching! :+1:
