### ISSUE TITLE
Accidental removing of favorites

### ISSUE THREAD

**Issue by jancborchardt** [light-launcher/Light-Android-Launcher#41]
It just happened to me that I accidentally long-pressed one of the favorites, and it vanished. I know that this is how you delete them, but it still felt strange.

Especially because to add the favorite back in its position (mine was in 2nd position of 5) you have to remove all the ones below too and add all of them again, this is very annoying.

It would be cool if there was a snack bar saying
> Removed `app name` from favorites  &nbsp; &nbsp; **Undo**

That way if it happens in error, it can be restored quickly.

**Comment by postapczuk** [comment]
done in 1.7
