### ISSUE TITLE
Orange highlight on press or long-press

### ISSUE THREAD

**Issue by jancborchardt** [light-launcher/Light-Android-Launcher#42]
When you press or long-press an entry, it gets an orange highlight background. This doesn’t really fit the style of Light Launcher.

Better would be to either just use white background – or maybe just underline it (like light phone does) as that’s not such a harsh change.

![light launcher underline](https://user-images.githubusercontent.com/925062/50017951-02325900-ffce-11e8-916f-d7e7e387d09b.png)

This article might be helpful: [ListView Tips & Tricks #3: Create Fancy ListViews](https://cyrilmottier.com/2011/08/08/listview-tips-tricks-3-create-fancy-listviews/)

**Comment by taylor-josh** [comment]
Hello. Could I have this issue assigned to me?
I have a small change which should satisfy this issue.
It's just a simple change to the selector for the listView but it looks much nicer

**Comment by postapczuk** [comment]
@taylor-josh I'll be able to do that if you accept to be collaborator (you shouls receive notification)

**Comment by taylor-josh** [comment]
Thanks!
I'll get my PR sent in after I get off work today for review.

**Comment by jancborchardt** [comment]
Awesome @taylor-josh, welcome! :) Looking forward to the fix
