### ISSUE TITLE
Swipe from buttom

### ISSUE THREAD

**Issue by nr458h** [light-launcher/Light-Android-Launcher#51]
In addition one question: in my opinion it is more comfortable to swipe from the buttom instead of left to right (this is also more easy for left-hander)

Probably this could be changed too?

**Comment by jancborchardt** [comment]
This is something I thought about too, especially considering that
- most Android launchers do have the extended list of apps on the bottom
- it could be seen as a continuation of the favorites list in the main view
- the ergonomics and muscle memory of swiping down are much more common than swiping to the sides

**Comment by postapczuk** [comment]
I think about adding the configuration view on swipe right - I think the all apps swiping direction could be added there. But i don't know how would you implement the swipe and decide to "load more favs" vs "all apps"

**Comment by nr458h** [comment]
I like the idea to see the swipe from the buttom es a continuation of the fav list. Especialy when #15 is implemented.

Then I do have my favorite apps on the homescreen and with one swipe all my apps sorted by frequenzy.

Sounds great or? :+1:
