### ISSUE TITLE
Add right padding

### ISSUE THREAD

**Issue by jurf** [light-launcher/Light-Android-Launcher#60]
Currently if the app name is just the right length it can almost touch the right screen border, which doesn’t look very pretty.

**Comment by jancborchardt** [comment]
Yes, good point! The padding on the right should be the same as on the left, with ellipsis if the name is too long.

@postapczuk what do you think? Where would this be changed?

**Comment by jancborchardt** [comment]
Or @jurf seeing as you also do development work, are you interested in opening a pull request for that? :)

**Comment by jurf** [comment]
@jancborchardt us much as I’d like to, I have never done any Android/Java development and I simply cannot find the time during the semester, sorry. I’m happy to help test the app/report bugs though.

**Comment by postapczuk** [comment]
solved in 1.7
