### ISSUE TITLE
Optimize colours in e-paper version

### ISSUE THREAD

**Issue by m4st3rP** [light-launcher/Light-Android-Launcher#61]
Since e-ink displays tend to have ghosting issues, it would make sense to change the colour of the background in the e-paper version to white and the font to black.

**Comment by postapczuk** [comment]
There is a transition between views, and it updates the ghosting - Are you sure you use the apk from the url link mentioned in README.md `E-paper version` section?

**Comment by ploum** [comment]
is it possible to have the e-ink version available on f-droid? The apk in the dropbox link isn't working for me.

**Comment by postapczuk** [comment]
I will check the issue with file, also to have it on fdroid I will need to create separate fork - will do this next week

**Comment by postapczuk** [comment]
@ploum from today e-paper version is maintained on the other repo: https://github.com/postapczuk/Light-ePaper-Launcher/tree/0.1.0

**Comment by postapczuk** [comment]
E-paper version is maintained on the other repo: https://github.com/postapczuk/Light-ePaper-Launcher/
