### ISSUE TITLE
Slow & No sort!

### ISSUE THREAD

**Issue by ShadyGaDa** [light-launcher/Light-Android-Launcher#65]
Was good. But with a lot of apps any movement brings ALL apps back in sluggish mode.
I can't move app order about, so bit nailed there. The DOUBLE selection mode also confusing, selecting/running....?
Will either wait for change uninstall or fork and deliberate.

**Comment by jancborchardt** [comment]
Hi @ShadyGaDa, this is a community project and we are all volunteers, so any contribution is very welcome. :)

Could you describe a bit more what you mean by your feedback?
- Where is something slow or sluggish? The apps itself, or scrolling the list? I haven’t seen anything like that yet, even on a quite old phone.
- Would you like to reorder the apps in the favorites view, or the "All apps" view?
- What do you mean by "double selection mode"?

Thanks! :)

**Comment by postapczuk** [comment]
I think he speaks "double mide" as no exclusion of selected apps in main view

**Comment by postapczuk** [comment]
Also problem with ordering comes again. Someone should work on that

**Comment by ShadyGaDa** [comment]
Swipe up brings selection screen, I have 500 apps, so every time it searches. The difference between select and run screens is a bit mystifying. I shall look at some of the choices I have seen.

**Comment by jancborchardt** [comment]
Right, so you mean it could cache the app list? Maybe that’s a good start.

**Comment by ShadyGaDa** [comment]
Yep, maybe left/right swipe for select and run.

**Comment by postapczuk** [comment]
I am pretty sure it is fixed as cache is used now, but no further info about this issue.

**Comment by postapczuk** [comment]
@ShadyGaDa 
> Was good. But with a lot of apps any movement brings ALL apps back in sluggish mode.
> I can't move app order about, so bit nailed there. The DOUBLE selection mode also confusing, selecting/running....?
> Will either wait for change uninstall or fork and deliberate.

I guess you don't understand how swipe to all apps works. If you swipe on favourites view from bottom to maximum half of screen you'll get all apps view, if you will do this from any place but futher than the half of the screen you will scroll over your favourites
