### ISSUE TITLE
unintended behavior

### ISSUE THREAD

**Issue by lieuxnoir** [light-launcher/Light-Android-Launcher#66]
Pressing the back key while on the home screen slides the home screen down, leaving a blank (black) background with nothing. However, pressing the home key while on this weird situation lifts the home screen back into its place.

**Comment by postapczuk** [comment]
Strange. I will check that. On my phone it just refresh the view again... no blank screen, but I will fix that

**Comment by jancborchardt** [comment]
For me it also refreshes the view, but even that is weird. On the favorites view, pressing the back button should not do anything (as it did before the latest release). :)

**Comment by postapczuk** [comment]
fixed in 1.7
