### ISSUE TITLE
System nav draws over launcher in Android 10

### ISSUE THREAD

**Issue by taylor-josh** [light-launcher/Light-Android-Launcher#75]
To repo:

1. Have Android 10

When in All Apps (assuming this happens in Favourites as well), if the amount of apps stretches to the bottom of the screen, the System nav bar draws over the launcher.

Example:
![Screenshot_20191111-012108](https://user-images.githubusercontent.com/39976320/69002612-c29c7d00-08c0-11ea-8d34-28c487c8b6e1.png)

From what I can see, this is because the flags in the OnCreate method are NO_LIMITS:

`this.getWindow().setFlags(
                FLAG_LAYOUT_NO_LIMITS,
                FLAG_LAYOUT_NO_LIMITS);`

Is there any reason that we have to use these flags that I am unaware of or can we this instead:

`this.getWindow().setFlags(
                FLAG_LAYOUT_IN_SCREEN,
                FLAG_LAYOUT_IN_SCREEN);`

I can't think of any reason why we need NO_LIMITS specifically.

**Comment by acorreya** [comment]
Having the same issue. Cannot acces the last item (want to uninstall zoom, but I will not able to get YouTube then)
![2020_04_10_17_25_24](https://user-images.githubusercontent.com/3225091/78989271-b1c7fe80-7b22-11ea-90b2-1a1542ccd246.jpg)

**Comment by taylor-josh** [comment]
I've actually been running the change that I proposed in my original post
with the different flags for a few months and I've not encountered any
problems. I can go ahead and get those changes checked in this weekend so
that the issue will be resolved for everyone.
