### ISSUE TITLE
Keyboard auto popups in all apps

### ISSUE THREAD

**Issue by drainboy** [light-launcher/Light-Android-Launcher#76]
i have two phones with light launcher installed. one constantly have the keyboard popping up while the other doesn't. however, i can't seem to see any difference with either set up. it's relly annoying cause it takes up a significance portion of the bottom half of the screen.

is there a way to disable auto keyboard popup?

**Comment by postapczuk** [comment]
Please check keyboard settings. It seems it's not  launcher issue - keyboard focus is disabled after loading all apps view

**Comment by postapczuk** [comment]
fixed - will be added in next release

**Comment by postapczuk** [comment]
@drainboy https://github.com/light-launcher/Light-Android-Launcher/releases/tag/1.8.5

**Comment by drainboy** [comment]
thank you for the fix
