### ISSUE TITLE
screen flashes when opening/closing the all app screen

### ISSUE THREAD

**Issue by BasilTomato** [light-launcher/Light-Android-Launcher#83]
There is a sudden white flash when opening/closing the all app screen if the "Remove animations" setting is set to "on".
This problem is barely visible if the remove animation is set to "off" and the opening/closing animation have time to complete.
The setting is located in the global Settings app, the Accessibility section.

**Comment by postapczuk** [comment]
Please provide android version

**Comment by BasilTomato** [comment]
OS: Android 10, Security update May 2020
 
phone: Xiaomi Mi A2 (Android One)

**Comment by postapczuk** [comment]
@BasilTomato I have Android 10 - tested and no issue with this. Could you confirm that this issue still appear?

**Comment by BasilTomato** [comment]
Yes, it is still present.
Android 10, Security update: Sept. 5, 2020
This is an Android One phone, amost AOSP experience.

The problem still disappears if I set the "Remove animations" to off.

**Comment by DigitalNXZ** [comment]
> @BasilTomato I have Android 10 - tested and no issue with this. Could you confirm that this issue still appear?

It's 2021 I can Confirm that this appears.

You just need to disable Animations.. I did over Dev Settings and Set a Image with bright Colors.. whoosh it flashes.. doesn't happen on dark images.

I my phone on dark mode if this should do somethin with it.. i just testet it with aniamtions off and on on a bright color images and on a dark colored image.

So 3 things
1. Dark Mode
2. Animations off
3. Background with bright colors as white

May you can reproduce it rn? :)

**Comment by postapczuk** [comment]
Ok I'll try to reproduce it. Thanks for details!

**Comment by postapczuk** [comment]
Sorry, no luck on reproducing this..

**Comment by BasilTomato** [comment]
In the meantime I have switched back the "Remove animations" setting to the default value (off), and the problem resolved.
This issue may be closed.
