### ISSUE TITLE
Different entries from a single package launch the same app

### ISSUE THREAD

**Issue by andis-sprinkis** [light-launcher/Light-Android-Launcher#87]
Application: Suntimes (F-Droid release)
https://f-droid.org/en/packages/com.forrestguice.suntimeswidget/
This package comes with 2 GUI applications - Suntimes and Suntimes Alarms.

**Issue:** In Light-Android-Launcher the "Suntimes Alarms" entry comes in the list right after "Suntimes" and it still launches "Suntimes".
I do not know if it is the above mentioned app package or the launcher issue.
With LineageOS (v17) stock launcher (Okular) each entry launches the correct app.

**Comment by postapczuk** [comment]
Just tested this and works correctly on both favs and all apps views.

**Comment by postapczuk** [comment]
I'm pretty sure it was fixed on some of the versions.
