### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [light-launcher/Light-Android-Launcher#89]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by postapczuk** [comment]
I pushed description and screenshots but this doesn't seem to work. is there something wrong with files structure? @mondlicht-und-sterne

**Comment by mondlicht-und-sterne** [comment]
maybe there was just no update to f-droid yet
