### ISSUE TITLE
Swipe to view all apps is not discoverable

### ISSUE THREAD

**Issue by jancborchardt** [light-launcher/Light-Android-Launcher#9]
Currently it’s impossible to know how to view all apps, unless you read the app description, which rarely people do. ;)

So we could display a hint like this, which could be visible until you opened the all apps list for the first time:

> ← Swipe to view all apps

![lightlauncher-swipe](https://user-images.githubusercontent.com/925062/49014446-74a6da80-f180-11e8-8ab5-2d8dcd894b8d.png)

**Comment by jancborchardt** [comment]
Similarly, we could show something like

> Long-press for app details

on the bottom of the all apps list as a permanent hint to know what to do. :)

**Comment by taylor-josh** [comment]
I can take a look at this

**Comment by taylor-josh** [comment]
To followup on this, @jancborchardt . Would it make sense to have the hint appear the first time or would we want it there permanently? Personally, I wouldn't want to keep seeing the hint.

A snackbar message would be pretty trivial to implement to run once but at the same time be pretty unobtrusive.

**Comment by jancborchardt** [comment]
> Would it make sense to have the hint appear the first time or would we want it there permanently? Personally, I wouldn't want to keep seeing the hint.

As said in the main issue text :)

> we could display a hint like this, which could be visible until you opened the all apps list for the first time

**Comment by taylor-josh** [comment]
I guess I should learn how to read 🤦

**Comment by postapczuk** [comment]
Following the issue I've fixed it the way other launchers do ( i guess it's intuitive ) - so added just small arrow on the bottom

**Comment by postapczuk** [comment]
also I've added on click to it
