### ISSUE TITLE
Launcher crashes sometimes, bug?

### ISSUE THREAD

**Issue by DigitalNXZ** [light-launcher/Light-Android-Launcher#91]
I tried to reproduce it but failed at it, I even tried to get some logs.. well way to hard.. since it happens rarely, but often enough to be annoying

the launcher crashes sometimes, I click on the Home Button or Kill Background Apps, after this I sometimes land on the default OS Launcher.. 

LightLauncher has no battery usage restriction, auto start and so on.. I had Nova Launcher before and it had no problems..

Does this app saves somewhere some Logs? Would like to provide them!

I have a Xiaomi 9T/K20 Pro

**Comment by postapczuk** [comment]
The most probably you don't have Light launcher set as default launcher. After crash system launches default launcher.
